In [ ]:
# =============================================================================
# ============================== 6. 넘파이(numpy) =============================
# =============================================================================

In [2]:
# numpy 불러와서 사용해보기
import numpy as np
np.array([1, 5, 7, 6]) #행벡터

array([1, 5, 7, 6])

In [3]:
np.array([1.25, 1, 5, 7]) #타입은 전체가 다 같아야함

array([1.25, 1.  , 5.  , 7.  ])

In [4]:
# numpy의 유용한 함수(방법)들
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [5]:
np.ones([2,3], dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.arange(0, 10, 2)   # 0 포함 O, 10 포함 X

array([0, 2, 4, 6, 8])

In [7]:
np.linspace(0, 1, 5)  # 0 포함 O, 10 포함 O

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.random.seed(12)

In [9]:
np.random.random((3,3))        # 3 by 3 U(0,1) 생성

array([[0.15416284, 0.7400497 , 0.26331502],
       [0.53373939, 0.01457496, 0.91874701],
       [0.90071485, 0.03342143, 0.95694934]])

In [14]:
np.random.normal(0, 1, (3,3))   # 3 by 3 N(0,1) 생성

array([[-0.61138674, -2.26090795,  1.31316866],
       [ 1.29948907,  0.48606528, -0.16382624],
       [ 0.30209188,  1.07495638, -0.88582519]])

In [12]:
np.random.randint(0, 9, (3,3)) # 3 by 3 정수(0-9) 생성

array([[0, 0, 8],
       [6, 1, 8],
       [4, 0, 4]])

In [17]:
rg = np.random.RandomState(40)  # np.random.RandomState 클래스를 rg로 객체화
rg.normal(0, 1, (3,3))

array([[-0.6075477 , -0.12613641, -0.68460636],
       [ 0.92871475, -1.84440103, -0.46700242],
       [ 2.29249034,  0.48881005,  0.71026699]])

In [1]:
# array의 객체화
import numpy as np
np.random.seed(1)
x = np.random.randint(10, size=(2,3,4))
print(x);print(x.ndim);print(x.shape);print(x.size)

[[[5 8 9 5]
  [0 0 1 7]
  [6 9 2 4]]

 [[5 2 4 2]
  [4 7 7 9]
  [1 7 0 6]]]
3
(2, 3, 4)
24


In [21]:
# array 접근과 편집(slicing)
x = np.array([0,3,5,2,4,6])  # 1차원
x[1]

3

In [24]:
x1=x[:,np.newaxis]
print(x1)
x2=x.reshape(6,1)
print(x2)
x3=np.reshape(x,(6,1))
print(x3)
x4=x3.flatten()
print(x4)

[[0]
 [3]
 [5]
 [2]
 [4]
 [6]]
[[0]
 [3]
 [5]
 [2]
 [4]
 [6]]
[[0]
 [3]
 [5]
 [2]
 [4]
 [6]]
[0 3 5 2 4 6]


In [25]:
x[1:3]   

array([3, 5])

In [26]:
x[1:-2]

array([3, 5, 2])

In [ ]:
x[::2]    # x[start:stop:step]

In [ ]:
x[:2]

In [ ]:
x[::-1]   # 역순으로

In [ ]:
x[5::-2]

In [4]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
x[:2, :2]

array([[1, 2],
       [4, 5]])

In [5]:
x[:, 0]   # 첫째 열

array([1, 4, 7])

In [6]:
x[0, :]   # 첫째 행

array([1, 2, 3])

In [7]:
x[0]

array([1, 2, 3])

In [8]:
x[1, 2]   # list에서는 x[1][2]로 같은 동작을 수행하였음

6

In [9]:
x[0, 0] = 99
x

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [10]:
x1 = x[:2, :2]
x1

array([[99,  2],
       [ 4,  5]])

In [11]:
x1[0, 1] = 99
x1

array([[99, 99],
       [ 4,  5]])

In [12]:
print(x)  # x1을 수정하면 x에도 반영이 됨. ∵뷰 형태로 x와 동일한 객체를 참조

[[99 99  3]
 [ 4  5  6]
 [ 7  8  9]]


In [13]:
print(id(x));print(id(x1))    # 주소는 x와 다름

1709719000368
1709720179376


In [14]:
x1_copy = x[:2, :2].copy()
x1_copy[0, 0] = 1000  # x에 영향을 주지 않음
print(x)

[[99 99  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
### 6.1 numpy의 차원 변경, 분할, 덧붙이기 ###

In [2]:
# 차원 변경
import numpy as np
x = np.array([1, 2, 3])
print(x)
x.reshape((1, 3))  # 2차원 행벡터화([]가 한 겹 더 생겼음)
print(x[np.newaxis, :]) #위와같음.
x.reshape((3, 1))  # 2차원 열벡터화
print(x[:, np.newaxis]) #위와같음.

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [3]:
x = np.random.randint(10, size=(3,3,4))
print(x)
print('---------------------------')
x1 = x.reshape((3, 12))  # 3 by 4 행렬의 각 행을 옆으로 붙임
print(x1)
print('---------------------------')
x2=x.reshape((-1,12))
print(x2)
print(np.shape(x2))
x.shape[1]

[[[6 5 1 2]
  [9 1 3 3]
  [5 1 8 1]]

 [[6 9 0 9]
  [6 5 1 7]
  [7 3 8 5]]

 [[4 9 3 8]
  [2 6 4 8]
  [8 1 7 9]]]
---------------------------
[[6 5 1 2 9 1 3 3 5 1 8 1]
 [6 9 0 9 6 5 1 7 7 3 8 5]
 [4 9 3 8 2 6 4 8 8 1 7 9]]
---------------------------
[[6 5 1 2 9 1 3 3 5 1 8 1]
 [6 9 0 9 6 5 1 7 7 3 8 5]
 [4 9 3 8 2 6 4 8 8 1 7 9]]
(3, 12)


3

In [4]:
# 분할
x = [1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [2,6])
print(x1, x2, x3)
x1[0] = 100  # 분할된 변수의 변경은 x에 반영되지 않음
print(x1)

[1 2] [3 4 5 6] [7 8]
[100   2]


In [5]:
x = np.random.random((4, 4));print(x)

[[0.37111712 0.89480109 0.97405571 0.07908467]
 [0.67297223 0.37611591 0.01586028 0.12030614]
 [0.36089377 0.81513041 0.50538287 0.85047402]
 [0.67496326 0.10717696 0.54076651 0.80872186]]


In [15]:
x1, x2 = np.vsplit(x, [2])  # 세로를 분할
print(x1)
print('--------------------------------------------------')
print(x2)

[[99 99  3]
 [ 4  5  6]]
--------------------------------------------------
[[7 8 9]]


In [6]:
y1, y2 = np.hsplit(x, [2])  # 가로를 분할
print(y1)
print('---------------------------')
print(y2)

[[0.37111712 0.89480109]
 [0.67297223 0.37611591]
 [0.36089377 0.81513041]
 [0.67496326 0.10717696]]
---------------------------
[[0.97405571 0.07908467]
 [0.01586028 0.12030614]
 [0.50538287 0.85047402]
 [0.54076651 0.80872186]]


In [7]:
# 덧붙이기
x = np.array([1, 2])
y = np.array([2, 3])
z = np.array([4, 5])
np.concatenate([x, y, z])

array([1, 2, 2, 3, 4, 5])

In [8]:
xx = np.array([[1,2,3], [4,5,6]])
yy = np.array([[2,4,6], [8,7,6]])
print(np.concatenate([xx, yy]))          # 아래로 붙임
print('---------------------------')
print(np.concatenate([xx, yy], axis=1))  # 옆으로 붙임

[[1 2 3]
 [4 5 6]
 [2 4 6]
 [8 7 6]]
---------------------------
[[1 2 3 2 4 6]
 [4 5 6 8 7 6]]


In [9]:
zz = np.array([55, 66, 77])
np.vstack([zz, xx])  # 세로로 쌓기. np.concatenate([zz.reshape((1,3)), xx])과 결과 동일

array([[55, 66, 77],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [ ]:
ww = np.array([[100], [200]])  # 열벡터
np.hstack([ww, xx])  # 가로로 쌓기

In [ ]:
### 6.2 numpy 연산 ###

In [10]:
x = np.array([1, 2, 3, 4])
print(x+3)
print(x-3)
print(x*3)
print(x/3)
print(x**3)
print(-(0.5*x+1)**2)

[4 5 6 7]
[-2 -1  0  1]
[ 3  6  9 12]
[0.33333333 0.66666667 1.         1.33333333]
[ 1  8 27 64]
[-2.25 -4.   -6.25 -9.  ]


In [11]:
print(np.exp(x))
print(np.power(3, x))
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 3  9 27 81]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]


In [12]:
M = np.ones((3, 3))
print(M)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
M1 = M + 1
print(M1)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [14]:
a = np.array([1, 2, 3])
M2 = M + a  # row by row로 연산 수행
print(M2)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [15]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a);print(b)
print('---------------------------')
print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
---------------------------
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [16]:
# 기초통계량 계산
np.random.seed(13)
x = np.random.randint(10, size=(3,4))
print(x)

[[2 0 0 6]
 [2 4 9 3]
 [4 2 6 5]]


In [17]:
print(np.sum(x))           # 원소의 총 합계
print(np.min(x, axis=1))   # 각 행의 최소값
print(np.mean(x, axis=0))  # 각 열의 평균
print(np.std(x, axis=0))   # 각 열의 표준편차

43
[0 2 2]
[2.66666667 2.         5.         4.66666667]
[0.94280904 1.63299316 3.74165739 1.24721913]


In [18]:
x_std = (x - np.mean(x, axis=0))/np.std(x, axis=0)
print(np.sum(x_std, axis=0))

[ 4.44089210e-16  0.00000000e+00  1.11022302e-16 -7.77156117e-16]


In [ ]:
### 6.2 논리 인덱싱(Boolean indexing)과 순서 정렬(Sorting) ###
x = np.array([[1,2,3,4], [5,6,7,8]]); print(x)

In [19]:
print(x >= 5)
print(np.sum(x>=5))
print(np.sum(x>=5, axis=1))  # 각 행별로 연산

[[False False False  True]
 [False False  True False]
 [False False  True  True]]
4
[1 1 2]


In [20]:
print(np.any(x>100))          
print(np.all(x<7, axis=0))   # 각 열별로 연산
print(np.all(x==100))

False
[ True  True False  True]
False


In [21]:
# 논리 인덱싱
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
y = np.array([1,0,1,0])
print(x[y==0, :])  # y=0인 행과 모든 열
print('---------------------------')
print(x[:, y==0])  # 모든 행과 y=0인 열

[[ 5  6  7  8]
 [13 14 15 16]]
---------------------------
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [22]:
# array를 활용한 인덱싱
x = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
ind1 = np.array([2, 3, 8])
ind2 = np.array([[2,1,3], [5,2,7]])
x1 = x[ind1]
x2 = x[ind2]
print(x1)
print('---------------------------')
print(x2)

[33 44 99]
---------------------------
[[33 22 44]
 [66 33 88]]


In [23]:
# 인덱싱에서의 브로드캐스팅
x = np.arange(12).reshape((3,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
y1 = np.array([1, 2, 2])
y2 = np.array([2, 0, 1])
print(y1[:,np.newaxis])
print(y2)
print(x[y1, y2])
print('---------------------------')
print(x[y1[:,np.newaxis], y2])

[[1]
 [2]
 [2]]
[2 0 1]
[6 8 9]
---------------------------
[[ 6  4  5]
 [10  8  9]
 [10  8  9]]


In [26]:
# 순서 정렬
x = np.array([2, 4, 3, 1, 5])
print(np.sort(x))

[1 2 3 4 5]


In [27]:
ind = np.argsort(x) # sort한 것의 index
print(ind) 

[3 0 2 1 4]
