In [1]:
import pandas as pd
import numpy as np

In [2]:
# 데이터 불러오기. y값은 이미 범주형으로 되어있음.
dat_wine=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/'
                     'wine/wine.data',header=None)
dat_wine.head()
dat_wine.columns = ['class label', 'alchohol', 'malic acid', 'ash', 
                    'alcalinity of ash', 'magnesium', 'total phenols', 
                    'flavanoids', 'nonflavanoid phenols', 
                    'proanthocyanins', 'color intensity', 'hue', 
                    'OD208', 'proline']  # Column names
print('class label:', np.unique(dat_wine['class label']))  # Class 출력
dat_wine.head()

class label: [1 2 3]


class label  alchohol  malic acid   ash  alcalinity of ash  magnesium  \
0            1     14.23        1.71  2.43               15.6        127   
1            1     13.20        1.78  2.14               11.2        100   
2            1     13.16        2.36  2.67               18.6        101   
3            1     14.37        1.95  2.50               16.8        113   
4            1     13.24        2.59  2.87               21.0        118   

   total phenols  flavanoids  nonflavanoid phenols  proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   color intensity   hue  OD208  proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735

In [3]:
# 전체 data를 training set과 test set으로 split
from sklearn.model_selection import train_test_split
X, y = dat_wine.iloc[:,1:].values, dat_wine.iloc[:,0].values #.value로 하면 pandas에서 numpy로 넘김.
X_train, X_test, y_train,y_test = \
    train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [4]:
# 표준화
from sklearn.preprocessing import StandardScaler #그러나, 굳이 표준화 안해도 됨.
std = StandardScaler()
X_train_std = std.fit_transform(X_train)
X_test_std = std.transform(X_test)

In [5]:
# Logistic Regression with L2 or L1 Regularization
from sklearn.linear_model import LogisticRegression
lr2_10 = LogisticRegression(penalty='l2', C=10.0)  # L2 with C(=1/λ)=10
lr2_1 = LogisticRegression(penalty='l2', C=1.0)    # L2 with C(=1/λ)=1
lr2_0_1 = LogisticRegression(penalty='l2', C=0.1)  # L2 with C(=1/λ)=0.1
lr1_10 = LogisticRegression(penalty='l1', C=10.0)  # L1 with C(=1/λ)=10
lr1_1 = LogisticRegression(penalty='l1', C=1.0)    # L1 with C(=1/λ)=1
lr1_0_1 = LogisticRegression(penalty='l1', C=0.1)  # L1 with C(=1/λ)=0.1

In [6]:
# 규제화 방법(L2 or L1)과 규제강도(λ)를 바꿔가며 accuracy score 계산
lr2_10.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test_std, y_test))

lr2_1.fit(X_train_std, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test_std, y_test))

lr2_0_1.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test_std, y_test))

lr1_10.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test_std, y_test))

lr1_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test_std, y_test))

lr1_0_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test_std, y_test))

Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9629629629629629
Training accuracy with L2 and λ=1: 1.0
Test accuracy with L2 and λ=1: 0.9814814814814815
Training accuracy with L2 and λ=10: 0.9919354838709677
Test accuracy with L2 and λ=10: 0.9814814814814815
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9814814814814815
Training accuracy with L1 and λ=1: 1.0
Test accuracy with L1 and λ=1: 0.9814814814814815
Training accuracy with L1 and λ=10: 0.9838709677419355
Test accuracy with L1 and λ=10: 1.0


C:\Users\82104\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\82104\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\82104\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\82104\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\82104\Anaconda3\envs\tensorflow\l

In [7]:
# L2 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[-1.95775485 -2.03400782 -3.43291968]
[-1.21122348 -1.03039089 -1.97016349]
[-0.60105075 -0.40659682 -0.88778119]
[[ 2.31301856  0.42623793  0.88915733 -2.72742063  0.34471977  0.57063457
   1.5328249  -0.05747067 -0.14460937  0.02365977 -0.1387799   1.54453754
   2.51006889]
 [-2.4473801  -1.00394827 -2.00966039  1.87532324 -0.35077231 -1.05421584
   1.79723557  0.73213183  0.6214013  -2.34983446  1.65715682  0.1387643
  -3.41020463]
 [ 0.6567932   0.46268852  1.37035647  0.34767553  0.30329156  0.47280507
  -3.25015231 -0.70851215 -0.5273707   1.92694485 -1.61435627 -1.42974821
   0.11678842]]
[[ 1.30549004  0.14549881  0.46036028 -1.44931922  0.10031419  0.36298361
   0.87213708 -0.11270049  0.02097189  0.09455712  0.05891572  0.8160453
   1.64325979]
 [-1.52090137 -0.57645877 -0.92554937  0.93057203 -0.32301482 -0.32640468
   0.67685016  0.31393307  0.31558446 -1.26644027  0.89364797  0.11339036
  -1.69368203]
 [ 0.36275758  0.42896676  0.49386343  0.31296385  0.264319   -0.0694720

In [8]:
# L2 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[-2.15539346 -2.65306223 -4.16710092]
[-1.1203623  -1.13569073 -2.22632818]
[-0.29624379 -0.08168112 -0.78574917]
[[ 2.94062319  0.26004102  1.13546263 -3.15468907  0.24200869  0.
   1.82807839  0.          0.          0.          0.          1.94412265
   3.25571958]
 [-2.86350002 -0.99937163 -2.64913224  1.98208927  0.         -0.93325401
   1.71131623  0.70533296  1.17288098 -3.43809554  2.33096144  0.
  -5.23641552]
 [ 0.91779844  0.19381083  1.91973486  0.          0.20582808  0.15851225
  -5.50285911 -0.94486753 -0.04405337  2.72497526 -1.5033196  -0.81563798
   0.        ]]
[[ 1.41253704  0.          0.28078988 -1.36316988  0.          0.
   1.26591075  0.          0.          0.          0.          0.71562607
   2.2193297 ]
 [-1.68977024 -0.37297406 -0.82508207  0.68131713 -0.12029266  0.
   0.39840869  0.01198618  0.24812436 -1.42652893  1.05868108  0.
  -2.22931465]
 [ 0.          0.23215342  0.5070737   0.          0.16161758  0.
  -2.48935201 -0.11884303  0.          1.650

In [9]:
lr2_10.fit(X_train, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test, y_test))

lr2_1.fit(X_train, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test, y_test))

lr2_0_1.fit(X_train, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test, y_test))

lr1_10.fit(X_train, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test, y_test))

lr1_1.fit(X_train, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test, y_test))

lr1_0_1.fit(X_train, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test, y_test))

Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9259259259259259
Training accuracy with L2 and λ=1: 0.9838709677419355
Test accuracy with L2 and λ=1: 0.9444444444444444
Training accuracy with L2 and λ=10: 0.9758064516129032
Test accuracy with L2 and λ=10: 0.9259259259259259
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9074074074074074
Training accuracy with L1 and λ=1: 0.9838709677419355
Test accuracy with L1 and λ=1: 0.9074074074074074
Training accuracy with L1 and λ=10: 0.9354838709677419
Test accuracy with L1 and λ=10: 0.8888888888888888


C:\Users\82104\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\82104\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\82104\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\82104\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\82104\Anaconda3\envs\tensorflow\l

In [10]:
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[-1.05564741  1.3348114  -0.22389541]
[-0.16655119  0.26945881 -0.07960021]
[-0.02988443  0.05684191 -0.02613036]
[[-8.35642949e-01  1.49521210e+00  1.52369353e+00 -1.27817609e+00
   2.25648654e-02  9.05116984e-01  3.08779561e+00 -9.33326494e-02
  -1.29875349e+00 -6.08125090e-01 -3.72175687e-02  5.33245210e-01
   2.71830334e-02]
 [ 1.15228208e+00 -2.15871624e+00 -1.17405523e+00  7.39159399e-01
  -1.89967112e-02 -1.03946174e+00  1.25486106e+00  2.83070658e+00
   1.61987199e+00 -2.56447479e+00  3.24685271e+00 -7.06694655e-01
  -2.26256260e-02]
 [-7.02384438e-01  1.19093319e+00  5.88075995e-01  4.04077810e-02
   7.27697470e-02 -3.70650449e-01 -3.76283098e+00 -6.02725274e-01
  -7.46355467e-01  1.33643076e+00 -1.36728910e+00 -2.11436644e+00
   2.98186158e-03]]
[[-3.58983950e-01  4.10637468e-01  3.53872093e-01 -7.42979348e-01
  -3.36933386e-02  5.44683231e-01  1.12999767e+00 -5.75279878e-02
   5.03329512e-02 -1.89873020e-01  7.55818485e-03  6.14639419e-01
   2.00108374e-02]
 [ 5.83710773e-01

In [11]:
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[[-1.00949168e+00  2.38825852e+00  1.52860100e-01 -1.85372296e+00
   8.31034645e-02  0.00000000e+00  7.12935988e+00  0.00000000e+00
  -2.97806319e+00 -8.15906320e-01  0.00000000e+00  0.00000000e+00
   3.48506779e-02]
 [ 1.32970129e+00 -2.75243104e+00 -3.36896109e+00  9.44685689e-01
  -1.97295873e-04 -1.96799011e+00  1.92259400e+00  1.24238167e+01
   2.61099154e+00 -3.26615076e+00  4.27523035e+00 -5.09307885e-01
  -2.75539293e-02]
 [-2.45709055e-01  1.37823812e+00  0.00000000e+00  3.70412064e-02
   1.15204434e-01  0.00000000e+00 -7.97089472e+00  0.00000000e+00
   0.00000000e+00  1.23522569e+00 -2.29034047e+00 -3.79322497e+00
  -6.63398637e-04]]
[[-2.28814977e-02  8.14093151e-02  0.00000000e+00 -7.05565543e-01
  -4.60400785e-02  0.00000000e+00  1.97049504e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.76173314e-02]
 [ 5.84883432e-01 -1.21360357e+00  0.00000000e+00  4.26300482e-01
   2.45595252e-02  0.00000000e+0